// Code generated by goxogen. DO NOT EDIT.
package {{.Package}}

import (
	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
	"github.com/nobuenhombre/suikat/pkg/ge"
    "github.com/nobuenhombre/suikat/pkg/db/types"
)

type Db{{.DbName}}Repo struct {
	db pgxdb.DBQuery
{{- range .Repos }}
	{{.}} I{{.}}Repository
{{- end }}
}

func NewDb{{.DbName}}Repository(config *pgxdb.Config, log types.SQLLoggerFunc) (*Db{{.DbName}}Repo, error) {
	db, err := pgxdb.New(config, log)
	if err != nil {
		return nil, ge.Pin(err)
	}

	return &Db{{.DbName}}Repo{
		db: db,
{{- range .Repos }}
		{{.}}: New{{.}}Repository(db),
{{- end }}
	}, nil
}

// Close closes the database connection.
func (dbRepo *Db{{.DbName}}Repo) Close() {
	dbRepo.db.Close()
}
