// Code generated by goxogen. DO NOT EDIT.
package {{.Package}}

import (
	"github.com/google/wire"
	pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
	"github.com/nobuenhombre/suikat/pkg/ge"
    "github.com/nobuenhombre/suikat/pkg/db/types"
)

// ProviderSet exports Wire providers for the generated package.
var ProviderSet = wire.NewSet(
	Provider{{.DbName}},
)

// Provider{{.DbName}} creates a Db{{.DbName}}Repo and returns it with a cleanup function.
func Provider{{.DbName}}(config *pgxdb.Config, log types.SQLLoggerFunc) (*Db{{.DbName}}Repo, func(), error) {
	dbRepo, err := NewDb{{.DbName}}Repository(config, log)
	if err != nil {
		return nil, nil, ge.Pin(err)
	}

	cleanup := func() {
		dbRepo.Close()
	}

	return dbRepo, cleanup, nil
}
