{{define "xouidpackage"}}
// Package {{ .Package }} contains the types for schema '{{ .Schema }}'.
package {{ .Package }}

// Code generated by xouid. DO NOT EDIT.

import (
    "context"
    "github.com/jackc/pgx/v5"
    "github.com/google/uuid"
    "github.com/lib/pq"
    pgxdb "github.com/nobuenhombre/suikat/pkg/db/connectors/postgres-pgx-db"
)

{{end}}
