// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"goxogen/src/internal/app/goxogen/cli"
	"goxogen/src/internal/app/goxogen/domain"
)

// Injectors from wire.go:

// initializeApp is the Wire injector entrypoint. It aggregates all ProviderSets
// and constructs the top-level application. No logic belongs here.
func initializeApp() (IApp, func(), error) {
	service, cleanup, err := cli.ProvideCLI()
	if err != nil {
		return nil, nil, err
	}
	domainService, cleanup2, err := domainapp.ProvideDomain(service)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iApp, cleanup3, err := newApp(domainService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return iApp, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
