// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"goxogen/src/internal/app/xouid/cli"
	"goxogen/src/internal/app/xouid/domain"
	"goxogen/src/internal/app/xouid/postgres"
)

// Injectors from wire.go:

// initializeApp is the Wire injector entrypoint for xouid.
// It aggregates all ProviderSets and constructs the top-level application.
func initializeApp() (IApp, func(), error) {
	service, cleanup, err := cli.ProvideCLI()
	if err != nil {
		return nil, nil, err
	}
	dbQuery, cleanup2, err := postgres.ProvideDB(service)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	domainService, cleanup3, err := domainapp.ProvideDomain(service, dbQuery)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	iApp, cleanup4, err := newApp(domainService)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return iApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
